### ISSUE TITLE
#Branche 29 - Redis::CannotConnectError in BooksController#update 

### ISSUE THREAD

**Issue by pierregambaud** [sebastiencarceles/books_odb#1]
Bonjour Sébastien,

Un message d'erreur apparaît lorsque j'essaie de modifier un livre.

![capture d ecran 2018-10-03 a 16 21 30](https://user-images.githubusercontent.com/10707119/46416744-6f04b980-c728-11e8-85bb-11d2e45cdb43.png)

Une idée pour la corriger ?

Merci d'avance !

Pierre

**Comment by sebastiencarceles** [comment]
Bonjour Pierre !

C'est un problème lié à Redis. Je pense qu'il n'est pas démarré. Est-il bien installé ?

Vous pouvez également vérifier qu'il fonctionne bien avec la commande `redis-cli ping`, qui devrait vous répondre "PONG".

Si vous n'avez pas Redis, vous pouvez suivre cette documentation pour l'installer et le configurer : https://medium.com/@petehouston/install-and-config-redis-on-mac-os-x-via-homebrew-eb8df9a4f298

Bon courage ! 
Sébastien

**Comment by pierregambaud** [comment]
Bonjour Sébastien,

Merci pour ce rapide retour et le lien !

Tout fonctionne à merveille en local à présent, au top 👍 

Bonne journée,

Pierre
